baseURL: https://examplesite.com
title: Known Unknowns
theme: somrat
paginate: '6'
summaryLength: '10'
disableLanguages: []
googleAnalytics: ''
disqusShortname: ''
outputs:
  home: HTML
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  author: somrat
  description: This is meta description
  favicon: images/favicon1.png
  logo_dark: images/logo-dark.png
  logo_light: images/logo.png
  logo_width: 150px
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap
      - link: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css
      - link: plugins/hover/hover.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/owl-carousel/owl.carousel.min.css
      - link: plugins/owl-carousel/owl.theme.default.min.css
      - link: plugins/text-animation/text-animation.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/wow.min.js
      - link: plugins/text-animation/text-animation.js
      - link: plugins/jquery.waypoints.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/owl-carousel/owl.carousel.min.js
  preloader:
    enable: yes
    preloader: images/logo.jpg
  social:
Languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com) <br> Known Unknowns is a registered UK Company (12599426)
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      main:
        - name: ABOUT
          pre: '#'
          url: about
          weight: 1
        - name: COMMIT NOW
          pre: '#'
          url: call-to-action
          weight: 2
        - name: INSTAGRAM
          pre: '#'
          url: "https://www.instagram.com/j_baisley_/"
          weight: 3
        - name: OFFERS
          pre: '#'
          url: "https://linktr.ee/JB.PT.Coach"
          weight: 3
    weight: 1

